### ISSUE TITLE
Arduino Pro Micro

### ISSUE THREAD

**Issue by Wallirec** [Wang-Derr/ARMIDUINO#2]
Wang-Derr, Hello! I wanted to make a compact controller and unknowingly bought an Aruduino micro with an ATmega32U4 controller. The sketch on the board works, the data is displayed on the LCD, but midi is not transmitted via USB, the Heduino firmware does not work on this board. Do you know how to make your USB sketch work on Arduino micro?

**Comment by Wang-Derr** [comment]
ATmega32U4 based controllers (like the Arduino Micro) have native USB capabilities, so instead of using the Hiduino project, you're alternatives are to either use a MIDI jack like I did or to use the [MIDIUSB library](https://github.com/arduino-libraries/MIDIUSB) in place of the the _MIDI.h_ library that this project relies on. Depending on how comfortable you are writing code, it shouldn't be too difficult to swap in the MIDIUSB library, this is the reference for it on Arduino's website: https://reference.arduino.cc/reference/en/libraries/midiusb/.

**Comment by Wallirec** [comment]
Unfortunately, I can't do this. We'll have to return to UNO and switch to a large building.
